---
apiVersion: v1
kind: Namespace
metadata:
  name: solo-validate-istio
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: solo-validate-istio
  namespace: solo-validate-istio

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: solo-validate-istio-role
  namespace: solo-validate-istio
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  - virtualservices
  verbs:
  - create
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - delete
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solo-validate-istio-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/portforward
  - pods/exec
  verbs:
  - "*"
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
  - install.istio.io
  resources:
  - istiooperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - envoyfilters
  verbs:
  - get
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: solo-validate-istio-binding
  namespace: solo-validate-istio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: solo-validate-istio-role
subjects:
- kind: ServiceAccount
  name: solo-validate-istio
  namespace: solo-validate-istio

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: solo-validate-istio-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: solo-validate-istio-cluster-role
subjects:
- kind: ServiceAccount
  name: solo-validate-istio
  namespace: solo-validate-istio
