---
apiVersion: v1
kind: Namespace
metadata:
  name: solo-validate-istio
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: solo-validate-istio
  namespace: solo-validate-istio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: solo-validate-ns-admin
  namespace: solo-validate-istio
subjects:
  - kind: ServiceAccount
    name: solo-validate-istio
    namespace: solo-validate-istio
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: solo-validate-istio-ns-admin
  namespace: istio-system
subjects:
  - kind: ServiceAccount
    name: solo-validate-istio
    namespace: solo-validate-istio
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: solo-validate-istio-istio-reader-system
subjects:
  - kind: ServiceAccount
    name: solo-validate-istio
    namespace: solo-validate-istio
roleRef:
  kind: ClusterRole
  name: istio-reader-istio-system
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: solo-validate-istio
  namespace: solo-validate-istio
  labels:
    app: solo-validate-istio
spec:
  serviceAccountName: solo-validate-istio
  containers:
    - name: solo-validate-istio
      image: soloio/support
      args: 
       - "sleep"
       - "9999"
      resources:
        requests:
          cpu: "100m"
          memory: "300Mi"
        limits:
          cpu: "500m"
          memory: "700Mi"
