---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: solo-validate-istio
  namespace: solo-validate-istio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: solo-validate-istio-istio-reader-system
subjects:
  - kind: ServiceAccount
    name: solo-validate-istio
    namespace: solo-validate-istio
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---